name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      ipfs:
        image: ipfs/go-ipfs:latest
        env:
          IPFS_PROFILE: server
        ports:
          - "5001:5001"

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'
    - run: npm ci
    - run: npm test
